import { Card } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header/Header'
import HomePage from '../components/Homepage/Homepage'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Pojištovací makléř | ITEAD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
      <footer >
       
      </footer>
    </div>
  )
}
